version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - addgroup
  - adduser
  - appendonly
  - appgroup
  - appuser
  - asasalint
  - asciicheck
  - azuretools
  - bidichk
  - bodyclose
  - canonicalheader
  - clickhouse
  - cockroachdb
  - containedctx
  - contextcheck
  - copyloopvar
  - cyclop
  - daixiang
  - dbmdl
  - decorder
  - depguard
  - dupl
  - dupword
  - durationcheck
  - eamodio
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - esbenp
  - ewrap
  - fatcontext
  - fieldalignment
  - FLUSHALL
  - FLUSHDB
  - forbidigo
  - forcetypeassert
  - funlen
  - gecos
  - ginkgolinter
  - gitversion
  - GITVERSION
  - GOARCH
  - gocheckcompilerdirectives
  - gochecknoglobals
  - gochecknoinits
  - gochecksumtype
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godox
  - GOFILES
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - golangci
  - GOMAXPROCS
  - gomoddirectives
  - gomodguard
  - GOPATH
  - goprintffuncname
  - GOPRIVATE
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - honnef
  - importas
  - inamedparam
  - ineffassign
  - interfacebloat
  - intrange
  - ireturn
  - isready
  - jackc
  - ldflags
  - loggercheck
  - maintidx
  - makezero
  - monngodb
  - musttag
  - mvdan
  - nakedret
  - nestif
  - nilerr
  - nilnil
  - nlreturn
  - noctx
  - nolintlint
  - nologin
  - nonamedreturns
  - nosprintfhostport
  - NOVENDOR
  - paralleltest
  - patroni
  - pbkit
  - perfsprint
  - pgxpool
  - prealloc
  - predeclared
  - promlinter
  - proto
  - protogetter
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - sslpassword
  - staticcheck
  - stdlib
  - stylecheck
  - tenv
  - testableexamples
  - testifylint
  - testpackage
  - thelper
  - toolstarget
  - toplevel
  - tparallel
  - trimpath
  - typecheck
  - unconvert
  - unparam
  - usestdlibvars
  - varnamelen
  - Warnf
  - wastedassign
  - wrapcheck
  - Wrapf
import: []
