action_id: trunk-whoami
date: 2024-10-23 11:40:07
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1729683607
full_timestamp:
  nanos: 433022000
  seconds: 1729683607
trunk_version: 1.22.6
